const tempkeywords = [
    "night", "fight", "good", "god", "love", "sex", "secret", "new", "death", 
    "man", "woman", "star", "doctor", "strikes", "show", "play", "girl", 
    "boy", "little", "adventure", "hero", "journey", "epic", "mystery", "romance", 
    "action", "thriller", "suspense", "magic", "war", "sci-fi", "comedy", "drama", 
    "tragedy", "crime", "horror", "legend", "quest", "history", "western", "musical", 
    "fantasy", "time", "space", "future", "past", "present", "battle", "sword", 
    "king", "queen", "prince", "princess", "monster", "zombie", "vampire", "alien", 
    "robot", "detective", "spy", "villain", "treasure", "curse",
    "said", "there", "use", "an", "each", "which", "she", "how",
    "some", "her", "would", "make", "like", "him", "into", "time", "look", 
    "two", "more", "write", "number","way", "could", "people", 
    "than", "first", "water", "been", "call", "who", "oil", "now", "find", 
    "long", "down", "day", "come", "made", "may", "part", "over", "new", 
    "sound", "take", "only", "little", "work", "know", "place", "year", "live",
    "back", "give", "most", "very", "after", "thing", "just", "name", "good", 
    "sentence", "man", "think", "say", "great", "where", "help", "through", "much", 
    "before", "line", "right", "means", "old", "any", "same", "tell", "boy", 
    "follow", "came", "want", "show", "also", "around", "form", "three", "small", 
    "set", "put", "end", "does", "another", "well", "large", "must", "big", "even", 
    "such", "because", "turn", "here", "why", "ask", "change", "went", "light", 
    "kind", "off", "house", "picture", "again", "animal", "point", 
    "mother", "world", "near", "build", "self", "earth", "father", "head", "stand", 
    "own", "page", "country", "found", "answer", "school", "grow", "study", 
    "still", "learn", "plant", "cover", "food", "sun", "four", "between", "state", 
    "keep", "eye", "never", "last", "thought", "city", "tree", "cross", "farm", 
    "hard", "start", "might", "story", "saw", "far", "sea", "draw", "left", "late", "run", 
    "don't"
  ];
  export default tempkeywords;